# 数据源配置
spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: ENC(OYfd8SGsOaHoEg5JAA2prYIa5Yt1NlnZ0+phKU4ev/oAqvLPvAaOu5ECea/o5dfFWJ1yk80Zgp8bL5Qj9c05bfP21ZxET9Xzr8YDbu1axnSXwSu6b5Pj2dMUhSIlFNLpfrQEfhcI38ch+y3tp0Z4TZsVQjECYycT)
      username: ENC(4y9Ze1pA9LhK35XabeKeeA==)
      password: ENC(uEzTgnletUJkM01XgGK8ofRqzIgxGEGT)
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #      aop-patterns: com.ky.zstu.service.*


      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,*.svg'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
  #Json时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 无视redis警告
  data:
    redis:
      repositories:
        enabled: false
  #redis配置
  redis:
    #数据库索引
    database: 0
    host: ENC(Au0eh4xlD0DY5rE0V3/MI9WwURgGqO6N)
    port: ENC(K+nO+pJckTgTp2WidMBpTA==)
    password: ENC(NRn1nrHXH9y840inHppxwtybofU5s5Go8eMTD1WylYCt82OIHRbrcQ==)
    #连接超时时间
    timeout: 5000

# mybatis配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.ky.ulearning.spi
